### ISSUE TITLE
Майнтейнер

### ISSUE THREAD

**Issue by JWo1F** [SortableJS/react-sortablejs#2]
День добрый, товарищи! Готовлю PR для биндинга.
Появился следующий вопрос: как именно лучше организовать бандл? Пакуем в него sortable? Или оставляем как peerDependency?

**Comment by RubaXa** [comment]
О, супер.
> peerDependency
> 

Да, паковать точно не нужно.

**Comment by JWo1F** [comment]
@RubaXa при тестировании заметил странный баг - как-то лагает сорт вниз. Запусти storybook из моей ветки, там это хорошо видно. Постараюсь прикрепить гифку чуть позже.

**Comment by JWo1F** [comment]
![nimbus-video](https://cloud.githubusercontent.com/assets/1540715/23679020/69b15c0a-0397-11e7-86fe-9a93d0976d0d.gif)

курсор немного лагает в записи, но я его плавно вел сначала сверху вниз, а потом наоборот. Скачки видно тут. Они есть и без биндинга.

**Comment by RubaXa** [comment]
Увы, я сейчас очень перегружен, сосем времени нет чтобы посмотреть.

**Comment by JWo1F** [comment]
@RubaXa думаю, надо переносить в основной sortable этот баг.
